server:
  port: 8082

spring:
  application:
    name: integracion-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

hda:
  pulsar:
    service-url: ${PULSAR_SERVICE_URL:pulsar://localhost:6650}
    admin-url: ${PULSAR_ADMIN_URL:http://localhost:8080}
    topic-trabajo-creado: persistent://hda/trabajos/trabajo-creado
    topic-trabajo-siniestro-creado: persistent://hda/integracion/trabajo-siniestro-creado
    subscription: integracion-service-sub
  idempotencia:
    ttl: PT24H

logging:
  level:
    org.apache.pulsar.client.impl.ProducerStatsRecorderImpl: WARN
    org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl: WARN
