server:
  port: 8083

spring:
  application:
    name: notificaciones-service
  data:
    redis:
      host: localhost
      port: 6379

hda:
  pulsar:
    service-url: pulsar://localhost:6650
    topic-trabajo-creado: persistent://hda/trabajos/trabajo-creado
    topic-notificacion-enviada: persistent://hda/notificaciones/notificacion-enviada
    subscription: notificaciones-service-sub
  idempotencia:
    ttl: PT24H

logging:
  level:
    org.apache.pulsar.client.impl.ProducerStatsRecorderImpl: WARN
    org.apache.pulsar.client.impl.ConsumerStatsRecorderImpl: WARN
