buildscript {
    ext {
        springBootVersion = '4.1.1'
        springDependencyManagementVersion = '1.1.7'
    }
}

plugins {
    id 'org.springframework.boot' version "${springBootVersion}" apply false
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}" apply false
}

allprojects {
    group = 'com.hda'
    version = '0.1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

ext {
    avroVersion = '1.12.1'
    pulsarReactiveVersion = '0.7.0'
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'

    java {
        toolchain {
            // Java 25 (LTS mas reciente al momento de esta entrega). Gradle descarga
            // el JDK automaticamente si no lo tienes instalado localmente.
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    dependencyManagement {
        imports {
            mavenBom "org.springframework.boot:spring-boot-dependencies:${springBootVersion}"
        }
    }

    dependencies {
        implementation 'io.projectreactor:reactor-core'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'io.projectreactor:reactor-test'
    }

    tasks.withType(Test).configureEach {
        useJUnitPlatform()
    }

    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs << '-parameters'
    }
}
