apply plugin: 'org.springframework.boot'

dependencies {
    implementation project(':integracion-model')
    implementation project(':integracion-usecase')
    implementation project(':integracion-pulsar-event-handler')
    implementation project(':integracion-pulsar-event-bus')
    implementation project(':integracion-redis-idempotency')

    implementation 'org.springframework.boot:spring-boot-starter' // @SpringBootApplication; nada mas lo trae aqui
    implementation 'org.apache.pulsar:pulsar-client-api' // PulsarClientConfig expone el bean PulsarClient
}

bootJar {
    archiveFileName = 'integracion-service.jar'
}
