server:
  port: 8085

spring:
  application:
    name: proveedor-service
  reactor:
    context-propagation: auto
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_PROVEEDOR_DB:hda_proveedor}
    username: ${POSTGRES_USER:hda}
    password: ${POSTGRES_PASSWORD:changeit}
  sql:
    init:
      mode: always   # ejecuta schema.sql al arrancar (crea la tabla y siembra los 2 proveedores si no existen)
      schema-locations: classpath:proveedor/schema.sql

hda:
  pulsar:
    service-url: ${PULSAR_SERVICE_URL:pulsar://localhost:6650}
    admin-url: ${PULSAR_ADMIN_URL:http://localhost:8080}
    topic-reservar-proveedor-command: persistent://hda/proveedor/reservar-proveedor-command
    subscription-reservar-proveedor-command: proveedor-reservar-command-sub
    topic-liberar-proveedor-command: persistent://hda/proveedor/liberar-proveedor-command
    subscription-liberar-proveedor-command: proveedor-liberar-command-sub
    topic-proveedor-reservado: persistent://hda/proveedor/proveedor-reservado
    topic-proveedor-no-disponible: persistent://hda/proveedor/proveedor-no-disponible
    topic-proveedor-liberado: persistent://hda/proveedor/proveedor-liberado

logging:
  level:
    org.apache.pulsar.client.impl.ProducerStatsRecorderImpl: WARN


management:
  endpoints:
    web:
      exposure:
        include: "health, metrics"
  endpoint:
    health:
      probes:
        enabled: false
      show-details: "always"
  metrics:
    enable:
      all: "${METRICS_ENABLE_ALL:true}"
  tracing:
    sampling:
      probability: "${OTEL_TRACING_SAMPLING:1.0}"
arconia:
  otel:
    exporter:
      type: otlp
    metrics:
      enabled: true
      exporter:
        interval: 60s
        otlp:
          endpoint: "${OTEL_COLLECTOR_HOST:http://localhost:4018}/v1/metrics"
          headers:
            Authorization: "${OTEL_EXPORTER_OTLP_HEADERS_AUTHORIZATION:Basic }"
    traces:
      enabled: true
      sampling:
        strategy: parent-based-trace-id-ratio
      exporter:
        otlp:
          endpoint: "${OTEL_COLLECTOR_HOST:http://localhost:4018}/v1/traces"
          headers:
            Authorization: "${OTEL_EXPORTER_OTLP_HEADERS_AUTHORIZATION:Basic }"
    logs:
      enabled: true
      exporter:
        otlp:
          endpoint: "${OTEL_COLLECTOR_HOST:http://localhost:4018}/v1/logs"
          headers:
            Authorization: "${OTEL_EXPORTER_OTLP_HEADERS_AUTHORIZATION:Basic }"
    resource:
      attributes:
        deployment.environment.name: "${SERVICE_ENV:local}"
        service.name: "${SERVICE_NAME:proveedor}"
